version: "3.9"
services:
  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    container_name: gateway
    ports:
      - "8090:8090"
    networks:
      - grpc-gw-tutorial
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: server
    ports:
      - "8080:8080"
    networks:
      - grpc-gw-tutorial

networks:
  grpc-gw-tutorial:
